[package]
name = "my-async"
version = "0.1.0"
authors = ["Po-Yeh Chen <smb374.cs08@nctu.edu.tw>"]
description = "An example async runtime that aims correctness & detailed documentation on underlying mechanisms."
readme = "README.md"
license = "MIT"
categories = ["asynchronous"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "~0.8"
futures-lite = "~1.12"
futures-task = "~0.3"
mio = { version = "~0.8", features = ["os-poll", "os-ext", "net"] }
nix = { version = "~0.24", features = ["fs"] }
num_cpus = "~1.13"
once_cell = "~1.9"
parking_lot = "~0.11"
rustc-hash = "~1.1"
tracing = "~0.1"
tracing-subscriber = { version = "~0.3", features = ["env-filter"] }
sharded-slab = "~0.1"
waker-fn = "~1.1"
