[package]
name = "my-async"
version = "0.1.0"
authors = ["Po-Yeh Chen <smb374.cs08@nctu.edu.tw>"]
description = "An example async runtime that aims correctness & detailed documentation on underlying mechanisms."
readme = "README.md"
license = "MIT"
categories = ["asynchronous"]
edition = "2021"

[dependencies]
crossbeam-deque = "~0.8"
crossbeam-utils = "~0.8"
flume = "~0.10"
futures-lite = "~1.12"
log = "~0.4"
mio = { version = "~0.8", features = ["os-poll", "os-ext", "net"] }
num_cpus = "~1.13"
once_cell = "~1.9"
parking_lot = "~0.11"
priority-queue = "~1.2"
rustc-hash = "~1.1"
rustix = { version = "~0.35", features = ["fs"] }
sharded-slab = "~0.1"
waker-fn = "~1.1"

[dev-dependencies]
assert_ok = "~1.0"
bytes = "*"
pin-project = "*"
tempfile = "~3.3"
